app = "miktex-api"
primary_region = "sin"  # Bạn có thể thay đổi thành region gần bạn nhất

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "miktex_data"
  destination = "/var/lib/miktex"
